### ISSUE TITLE
5. 10(일) 결과

### ISSUE THREAD

**Issue by trizdreaming** [SADANG-HOBBITS/Documents#1]
1. 문서 읽고 주제 만들기
   http://arthurtw.github.io/2014/12/21/rust-anti-sloppy-programming-language.html
   (http://stackoverflow.com/questions/24253344/move-vs-copy-in-rust/24253573#24253573)
   http://arthurtw.github.io/2014/11/30/rust-borrow-lifetimes.html
2. rust 원래 코드에 sort 보기

**Comment by YoonSung** [comment]
3.Priority Queue (min heap) 만들기
