### ISSUE TITLE
5. 30(토) 결과

### ISSUE THREAD

**Issue by trizdreaming** [SADANG-HOBBITS/Documents#3]
1. 정윤성 응답하라!!
2. rsoup 분량 정리
   - 김성환 : stringUtil
   - 최경욱 : node
   - 신동찬 : dataUtil, validation
3. 야구게임 format 코드 채우기
   - pattern match 로직 정리
   - 함수 등 네이밍

**Comment by YoonSung** [comment]
헐 이제야 봤네요 이걸ㅋㅋㅋ;
